export const lightTheme = {
    background: '#ffffff',
    foreground: '#333333',
    card: '#ffffff',
    cardForeground: '#333333',
    popover: '#ffffff',
    popoverForeground: '#333333',
    primary: '#4285F4',
    primaryForeground: '#ffffff',
    secondary: '#f5f5f5',
    secondaryForeground: '#333333',
    muted: '#f5f5f5',
    mutedForeground: '#333333',
    accent: '#f5f5f5',
    accentForeground: '#333333',
    destructive: '#d32f2f',
    destructiveForeground: '#ffffff',
    border: '#cccccc',
    input: '#f5f5f5',
    ring: '#4285F4',
    radius: 10,
};

export const darkTheme = {
    background: '#000',
    foreground: '#ffffff',
    card: '#333333',
    cardForeground: '#ffffff',
    popover: '#333333',
    popoverForeground: '#ffffff',
    primary: '#4285F4',
    primaryForeground: '#ffffff',
    secondary: '#1a1a1a',
    secondaryForeground: '#ffffff',
    muted: '#1a1a1a',
    mutedForeground: '#cccccc',
    accent: '#1a1a1a',
    accentForeground: '#ffffff',
    destructive: '#d32f2f',
    destructiveForeground: '#ffffff',
    border: '#444444',
    input: '#1a1a1a',
    ring: '#4285F4',
    radius: 10,
};
